sudo: required
services:
   - docker


before_install: 
  - docker build -t hkaled/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run hkaled/react-test  npm test -- --coverage 


after_success:
  - docker build -t hkaled/multi-client ./client
  - docker build -t hkaled/multi-nginx ./nginx
  - docker build -t hkaled/multi-server ./server
  - docker build -t hkaled/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hkaled/multi-client
  - docker push hkaled/multi-nginx
  - docker push hkaled/multi-server
  - docker push hkaled/multi-worker