sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t khaledkhaled/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true khaledkhaled/react-test npm test

after_success:
  - docker build -t khaledkhaled/multi-client ./client
  - docker build -t khaledkhaled/multi-nginx ./nginx
  - docker build -t khaledkhaled/multi-server ./server
  - docker build -t khaledkhaled/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push khaledkhaled/multi-client
  - docker push khaledkhaled/multi-nginx
  - docker push khaledkhaled/multi-server
  - docker push khaledkhaled/multi-worker



deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-841402626865'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
